# New & Sentiement Ingestion

In the notebook we will ingest some New and Sentiement data from Alpha Advantage. We will deep dive ingesting some New and Sentiement data across different sectors . For More follow this [link](https://www.alphavantage.co/documentation/)

In [11]:
import os
from dotenv  import load_dotenv
import requests
import pandas as pd

## 1. Blockchain :

In [12]:
# Getting API keys
#Load the enviormnet variable for this file
load_dotenv()

#Get env key
AlphaKey = os.getenv('AlphaAdvantage')

In [ ]:
url = f'https://www.alphavantage.co/query?function=NEWS_SENTIMENT&topics=blockchain&apikey={AlphaKey}'
r = requests.get(url)
data = r.json()

BlockChainDf = pd.DataFrame(data)
BlockChainDf.head(10)

,items,sentiment_score_definition,relevance_score_definition,feed
0,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Crypto Regulation Tanked Financial-...
1,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...","{'title': 'CoreWeave, Inc.', 'url': 'https://w..."
2,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Tom Lee's BitMine Stock Crashed Bel...
3,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'MSTX Lost 89 Percent From Its Augus...
4,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'TeraWulf Expands Beyond Bitcoin Min...
5,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Galaxy Digital tops quant-rated cry...
6,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Volatility Shares 2x Ether ETF drop...
7,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'CLARITY Act chances of passage this...
8,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Marathon Digital Holdings Stock (MA...
9,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...","{'title': '2x Bitcoin Strategy ETF ETF Price, ..."

## 2. Earnings Data

In [17]:
url = f'https://www.alphavantage.co/query?function=NEWS_SENTIMENT&topics=earnings&apikey={AlphaKey}'
r = requests.get(url)
data = r.json()

EarningsDf = pd.DataFrame(data)
EarningsDf.head(10)

,items,sentiment_score_definition,relevance_score_definition,feed
0,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'CVS Health Corporation $CVS Shares ...
1,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Aufman Associates Inc Has $1.27 Mil...
2,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Industry-first onsemi tool helps de...
3,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Havemeyer Place LP Invests $2.01 Mi...
4,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Morgan Stanley initiates GMR Soluti...
5,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'PPL Corp. (PPL) Appears Attractive ...
6,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'BMO Capital Reaffirms Outperform Ra...
7,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Long term debt to total equity rati...
8,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...","{'title': 'Plug Power, A.H.T. Syngas, and Cons..."
9,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'KeyCorp Comments on Salesforce's Q3...

## 3.IPO

In [ ]:
url = f'https://www.alphavantage.co/query?function=NEWS_SENTIMENT&topics=ipo&apikey={AlphaKey}'
r = requests.get(url)
data = r.json()

IPODf = pd.DataFrame(data)
IPODf.head(10)

,items,sentiment_score_definition,relevance_score_definition,feed
0,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Morgan Stanley initiates Cerebras s...
1,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...","{'title': 'CoreWeave, Inc.', 'url': 'https://w..."
2,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Markets Brief: Why Are Financial St...
3,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'A Look At RenaissanceRe Holdings (R...
4,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Assessing EHang Holdings (EH) Valua...
5,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'XBCVX Stock Fund Price and Chart — ...
6,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Assessing UroGen Pharma (URGN) Valu...
7,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Volatility Shares 2x Ether ETF drop...
8,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'WD-40 Company (WDFC) Valuation Chec...
9,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...","{'title': 'After a 2.6% Friday Plunge, the iSh..."

## 4. Merger and Aquisitions

In [21]:
url = f'https://www.alphavantage.co/query?function=NEWS_SENTIMENT&topics=mergers_and_acquisitions&apikey={AlphaKey}'
r = requests.get(url)
data = r.json()

MADf = pd.DataFrame(data)
MADf.head(10)

,items,sentiment_score_definition,relevance_score_definition,feed
0,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Morgan Stanley initiates Cerebras s...
1,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'NextEra Energy (NEE) Offers Potenti...
2,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Cancer fight: Roche agrees $700M up...
3,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Roche teams with Nurix on pill for ...
4,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Weatherford International To Acquir...
5,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'QUALCOMM Incorporated Shs Canadian ...
6,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Nippon Life Insurance And Blackston...
7,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'General Mills to sell Häagen-Dazs s...
8,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Analog Devices’ AI Power Push And E...
9,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...","{'title': 'S&P revises Butterfield outlook', '..."

## 5. Finaical Markets

In [23]:
url = f'https://www.alphavantage.co/query?function=NEWS_SENTIMENT&topics=financial_markets&apikey={AlphaKey}'
r = requests.get(url)
data = r.json()

FinancialMarketsDF = pd.DataFrame(data)
FinancialMarketsDF.head(10)

,items,sentiment_score_definition,relevance_score_definition,feed
0,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'CVS Health Corporation $CVS Shares ...
1,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Aufman Associates Inc Has $1.27 Mil...
2,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Industry-first onsemi tool helps de...
3,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Crypto Regulation Tanked Financial-...
4,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Morgan Stanley initiates Cerebras s...
5,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'WEC Energy Group (WEC) Offers a Com...
6,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Havemeyer Place LP Invests $2.01 Mi...
7,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Barclays Reiterates Overweight Rati...
8,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...","{'title': 'CoreWeave, Inc.', 'url': 'https://w..."
9,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'NextEra Energy (NEE) Offers Potenti...

## 6. Economy Fiscal

This covers Fiscal Policy related data

In [26]:
url = f'https://www.alphavantage.co/query?function=NEWS_SENTIMENT&topics=economy_fiscal&apikey={AlphaKey}'
r = requests.get(url)
data = r.json()

FiscalDataDf = pd.DataFrame(data)
FiscalDataDf.head(10)

,items,sentiment_score_definition,relevance_score_definition,feed
0,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'PGE proposes whopping 29% rate hike...
1,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Public Storage Looks Good But Buy T...
2,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'TVA gets $46M to revive Cumberland ...
3,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': '5 Best Quantum Computing Stocks to ...
4,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Walmart (NASDAQ: WMT) And Procter &...
5,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Why Bill to End Truck Tax Matters f...
6,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Deere & Co (DE) Stock Is a Tariff S...
7,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': '14 AI Stocks Making Headlines on Wa...
8,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'DOE Selects Hallador Energy for $27...
9,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': '3M targeted by Australia's biggest-...

## 7. Monetary Economy

This covers the Goverment intrest rate and inflation data.

In [27]:
url = f'https://www.alphavantage.co/query?function=NEWS_SENTIMENT&topics=economy_monetary&apikey={AlphaKey}'
r = requests.get(url)
data = r.json()

MonetaryPolicyDf = pd.DataFrame(data)
MonetaryPolicyDf.head(10)

,items,sentiment_score_definition,relevance_score_definition,feed
0,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Will NASDAQ Shockwave Burst AI Bubb...
1,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Markets Brief: Why Are Financial St...
2,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Costco quietly rolls back prices on...
3,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Why Newmont (NEM) Is Down 9.2% Afte...
4,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Strong Jobs Report Sends Applied Di...
5,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Is VICI Properties Inc. (VICI) A Go...
6,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'PBW’s 34% Year-to-Date Gain Masks a...
7,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'NUGT Collapsed 17% on Friday While ...
8,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'MSTX Lost 89 Percent From Its Augus...
9,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Calendar Clash: VanEck's Dividend H...

## 8. Macro Economy

In [28]:
url = f'https://www.alphavantage.co/query?function=NEWS_SENTIMENT&topics=economy_macro&apikey={AlphaKey}'
r = requests.get(url)
data = r.json()

MacroData = pd.DataFrame(data)
MacroData.head(10)

,items,sentiment_score_definition,relevance_score_definition,feed
0,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Williams-Sonoma (WSM) – Among the 1...
1,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Duke Energy Urges Customers to Cut ...
2,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Markets Brief: Why Are Financial St...
3,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'How Investors Are Reacting To KeyCo...
4,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Brazil’s Embraer sees eventual Chin...
5,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Will Q1 Beat And Timberland Sale Re...
6,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'MP Materials Corp Registered Shs Ce...
7,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'United Airlines unlikely to pursue ...
8,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Why Analysts Are Still Bullish On U...
9,50,x <= -0.35: Bearish; -0.35 < x <= -0.15: Somew...,"0 < x <= 1, with a higher score indicating hig...",{'title': 'Centene (CNC) Earns A Spot On Bank ...